### ISSUE TITLE
Castle 3.0.8 references nonexistant BCSymbolMaps folder

### ISSUE THREAD

**Issue by tiwoc** [castle/castle-ios#105]
Xcode 15 doesn't support Bitcode anymore, but the Highwind XCFramework still references a BCSymbolMaps folder that doesn't exist, breaking the build.

Repro steps with Xcode 15.2 (15C500b) and 15.3 RC (15E5202a):
- Create new iOS project
- Add `https://github.com/castle/castle-ios` package dependency, setting the version to 3.0.8
- Import Castle in one of the files
- Build

Error:
> Missing path (redacted/SourcePackages/checkouts/castle-ios/Castle/Highwind.xcframework/ios-arm64_x86_64-simulator/BCSymbolMaps) from XCFramework 'Highwind.xcframework' as defined by 'BitcodeSymbolMapsPath' in its `Info.plist` file

---

What I find particularly concerning with this issue is that if Castle would have run super basic tests before publishing the new release, basically just trying to actually pull the SDK into an app, this would have been caught before the release. May I ask you what your QA process is?

**Comment by aalekz** [comment]
Hi @tiwoc!

Thank you for reporting the issue and I apologize for the inconvenience it have caused.

I'll update the libraries and disable bitcode since it's deprecated.

In regards to our testing procedures we have extensive automated tests but we also have manual integration tests where we test integrating the SDK using CocoaPods, SwiftPM and manually adding the framework. The CocoaPods integration is included in our automated tests but the SwiftPM integration is still manually verified. Obviously we've missed a step when verifying the 3.0.8 version of the SDK and I apologize for that. I will work on automating the manual tests so that we can avoid any similar issues in the future.

**Comment by aalekz** [comment]
Hello again @tiwoc!

Sorry for the delay but there is now a new version available of the SDK that does not include any BCSymbolMaps. I've tested using SwiftPM and the latest version of Xcode and everything works great.

Thanks again for taking the time to report this issue and I apologize for any convenience it caused you.

Take care!

**Comment by tiwoc** [comment]
Thank you so much, @aalekz! I can confirm that 3.0.9 works great for us.
