### ISSUE TITLE
Framework won't compile because `Castle.m` and `CastleConfiguration.m` are missing

### ISSUE THREAD

**Issue by dabrut** [castle/castle-ios#49]
Hello 👋 ,

I've just updated the framework from 1.0.7 to 1.0.9 in my project and I'm now getting compilation errors because `Castle.m` and `CastleConfiguration.m` cannot be found.

From what I can tell, the files are there but are not in the `Public` folder anymore (the folder actually doesn't exist anymore).
I'm not sure if the `Public` folder should be recreated and the files moved into it or if the Xcode project itself should be updated to point to the new paths.

Could someone tell me what's the recommended way?

Thanks 🙂

**Comment by aalekz** [comment]
Hey @dabrut!

I'm sorry that you're experiencing issues upgrading. It seems I had missed to update Castle.xcodeproj to reflect the path change for CastleConfiguration and Castle files.

Since the Cocoapods installation procedure seems to be working without issue I'm assuming you're using carthage. I've opened a new pull request with a fix (https://github.com/castle/castle-ios/pull/50). I would appreciate it very much if you  could try using that branch `fix/carthage-build-1.0.9` and verify that the fix works on your end as well.

Thanks!

**Comment by dabrut** [comment]
Yep that branch works now 👍 
Thank you @aalekz
