### ISSUE TITLE
1.0.10 release tag doesn't contain Package.swift manifest

### ISSUE THREAD

**Issue by appsandwich** [castle/castle-ios#54]
Hi, the `1.0.10` tag was created before the `Package.swift` file was added to the repo, which prevents us from using SwiftPM to import that specific version. 

We currently have to use a specific revision (`f7c6cccae74c8aa9597101664981ea69f8d7d460`) in our Xcode config. We'd previously been pulling in `master`, but todays changes seem to be breaking our CI builds.

Could you please move the `1.0.10` tag to point to f7c6cccae74c8aa9597101664981ea69f8d7d460? Thanks!

**Comment by aalekz** [comment]
Hi, thank you for reporting this issue! I've update the tag now to point to f7c6ccc.

We had an issue with the 2.0.0 release when using SwiftPM, should be fixed in [19d97d1](https://github.com/castle/castle-ios/commit/19d97d1fa865bc798ef7fb3ac5490e61b4b4f8ec). I had to move the 2.0.0 tag after the fix so it could be that your CI is caching the old broken one.

Please let me know if this fixed your issues and I'll close the issue :)

**Comment by appsandwich** [comment]
Thanks so much @aalekz -- appreciate the quick response! 

I've just tested a CI build pointed to the updated 1.0.10 tag, and it's building without issue. Thanks again 👍

**Comment by aalekz** [comment]
Glad to hear that! Thanks for reporting the issue.

**Comment by tiwoc** [comment]
I wanted to report back about the breakage this change created for CocoaPods users.

CocoaPods expects releases to not change after the fact. It caches them locally in `~/Library/Caches/CocoaPods`. So, if you previously installed the Castle 1.0.10 pod, it will just reinstall the cached version and not the one newly tagged as 1.0.10 in the repo. If you're starting with a clean cache (in CI for example), it will happily install the new version and run with that, even if using the pinned version from Podfile.lock via `pod install`. You're effectively running different code locally and in production at this point.

**Problem 1:** We had (the previous version of) 1.0.10 included in a release that already went through extensive QA and beta testing. If the Castle pod is silently replaced with a newer version with the same version number, new issues could be introduced that slip through testing that way.

----

Then, there's another complication, and this is the reason why we noticed the modification in the first place: CocoaPods not only caches the extracted Castle pod locally, it also [caches the podspec in its repo](https://github.com/CocoaPods/Specs/blob/master/Specs/1/1/0/Castle/1.0.10/Castle.podspec.json). This podspec is out of date in that it includes this line:

```
"source_files": "Castle/Classes/**/*"
```

In the newer version of 1.0.10, the location of the source files changed to `Castle/**/*{h,m}`.

**Problem 2:** If you try to install Castle 1.0.10 with a clean CocoaPods cache, it will use the old version of the podspec file from the `CocoaPods/Specs` repository, but look for files in `Castle/Classes/**/*`. Since the `Classes` directory doesn't exist anymore in the newer 1.0.10 release, you end up with a Castle install that is missing all code files. CocoaPods doesn't print an error in this case, but when you try to build your app that uses Castle, you'll see this error message:

> No such module ‘Castle’

----

It took us hours to diagnose these issues on our end. Here's the workaround we came up with, to be put in the `Podfile`:
```
pod 'Castle', :git => 'https://github.com/castle/castle-ios.git', :commit => '5c678b97dc7c13e689a51c40f2d0dd88138d011f'
```

This forces CocoaPods to install the old version of the 1.0.10 that already went through our QA and beta process.

----

Thanks for making it through this postmortem. To prevent issues like these, I would like to ask you to not move a release tag in the future, but rather release a new version if there's anything that should be changed about an existing release.

**Comment by tkrajcar** [comment]
Hi @tiwoc - I run engineering here at Castle. I just wanted to say thanks for the very detailed and thoughtful writeup, and I'm sorry that we caused you and your team a lot of time chasing down a frustrating stray issue like this. I've made sure and reinforced with the team that we don't change published versions (regardless of language/platform) in the future.

**Comment by aalekz** [comment]
Hey @tiwoc!

Just wanted to personally apologize for this and I'm sorry that you and your team had to spend time to track the issue down. I should have obviously considered the implications of moving the tag before doing so.

I'll make sure to follow your advice and make sure not to make the same mistake in the future.

And thank you for your thorough write up of the issue and the implications!

If there is anything I can help you and your team with, just let me know!

**Comment by tiwoc** [comment]
Thanks, @tkrajcar and @aalekz! No hard feelings on my side.
