### ISSUE TITLE
Print object (po) not working - couldn't IRGen expression - GeoZip

### ISSUE THREAD

**Issue by acportela** [castle/castle-ios#66]
Hi, we're having the following problem with the current version of Castle (2.1.1)

```
(lldb) po foo
error: virtual filesystem overlay file '/Users/aLxx/Library/Developer/Xcode/DerivedData/GeoZip-gmzzobmowdxwazcweczokysrlzmm/Build/Intermediates.noindex/ArchiveIntermediates/GeoZip/IntermediateBuildFilesPath/GeoZip.build/Release-iphonesimulator/GeoZip.build/all-product-headers.yaml' not found

error: couldn't IRGen expression. Please check the above error messages for possible root causes.
```

Going back to 2.1.0 seems to fix the issue.

Thanks in advance.

**Comment by aalekz** [comment]
Hey @acportela!

I'll investigate this and get back to you, thanks for reporting!

**Comment by aalekz** [comment]
It seems like this is an issue related to lldb. This is what I've found:

1. https://pspdfkit.com/guides/ios/knowledge-base/debugging-issues/
2. https://stackoverflow.com/questions/54776459/whats-the-solution-for-error-couldnt-irgen-expression-no-additional-error/61824142#61824142
3. https://steipete.com/posts/couldnt-irgen-expression/

It seems to only occur in pure swift projects and adding a bridging header seem to "fix" the issue. I'll verify and test this case in an upcoming release so that this won't occur in future releases.
